### ISSUE TITLE
TypeError: cannot pickle 'WeakMethod' object

### ISSUE THREAD

**Issue by Grandzxw** [alvariseppanen/4DenoiseNet#11]
Traceback (most recent call last):
  File "/home/hit/code/4DenoiseNet-main/networks/train/tasks/semantic/./train.py", line 186, in <module>
    trainer.train()
  File "/home/hit/code/4DenoiseNet-main/networks/train/tasks/semantic/../../tasks/semantic/modules/trainer.py", line 309, in train
    save_checkpoint(state, self.log, suffix="")
  File "/home/hit/code/4DenoiseNet-main/networks/train/tasks/semantic/../../tasks/semantic/modules/trainer.py", line 69, in save_checkpoint
    torch.save(to_save, logdir + "/FourDenoiseNet" + suffix)
  File "/home/hit/anaconda3/envs/Denoise/lib/python3.9/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/hit/anaconda3/envs/Denoise/lib/python3.9/site-packages/torch/serialization.py", line 653, in _save
    pickler.dump(obj)
TypeError: cannot pickle 'WeakMethod' object

What is the specific environment you are running in? Can you update it on the readme. My environment is torch2.0.0, cuda11.8,python 3.9

**Comment by 15116513319** [comment]
I have also encountered the same problem. Have you resolved it？
