### ISSUE TITLE
TypeError: cannot pickle 'WeakMethod' object

### ISSUE THREAD

**Issue by 15116513319** [alvariseppanen/4DenoiseNet#14]
Hi @alvariseppanen, thank you for open-sourcing your work!

I have a questions regarding this work:

Traceback (most recent call last):
  File "./train.py", line 163, in <module>
    trainer.train()
  File "/home/wxq/wangxinqi/4DenoiseNet-main/networks/train/tasks/semantic/../../tasks/semantic/modules/trainer.py", line 283, in train
    save_checkpoint(state, self.log, suffix="")
  File "/home/wxq/wangxinqi/4DenoiseNet-main/networks/train/tasks/semantic/../../tasks/semantic/modules/trainer.py", line 57, in save_checkpoint
    torch.save(to_save, logdir +
  File "/home/wxq/archiconda3/envs/tensorflow/lib/python3.8/site-packages/torch/serialization.py", line 436, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/wxq/archiconda3/envs/tensorflow/lib/python3.8/site-packages/torch/serialization.py", line 648, in _save
    pickler.dump(obj)
TypeError: cannot pickle 'WeakMethod' object

Thanks again and looking forward to your reply!

**Comment by 15116513319** [comment]
已解决
